Disable use headermap in xcode so file indexing will have a closer co…
bazel-ios/rules_ios pull request #131
Opened 2020-10-05 16:43 UTC by gyfelton

…mpiling behaviour to Bazel side

2020-10-05 16:43 UTC, gyfelton commented
See whether testings are green

2020-10-06 18:32 UTC, segiddins requested changes
Discussed offline -- this almost  certainly requires passing in the private headermap for the target being built in `USER_HEADER_SEARCH_PATHS`

2020-10-08 02:34 UTC, amberdixon commented
I think the only thing you need to do in order to land this change is the following:

```
~/Development/rules_ios disable_using_headermap_in_xcode * git diff
diff --git a/rules/xcodeproj.bzl b/rules/xcodeproj.bzl
index 53f706a..07dc155 100644
--- a/rules/xcodeproj.bzl
+++ b/rules/xcodeproj.bzl
@@ -267,7 +267,7 @@ def _framework_search_paths_for_target(target_name, all_transitive_targets):
                 framework_search_paths.append("\"%s\"" % fi)
     return " ".join(framework_search_paths)
 
-def _header_search_paths_for_target(target_name, all_transitive_targets):
+def _header_search_paths_for_target(target_name, all_transitive_targets, include_wksp_root = True, hmap_name_filter = None):
     """Helper method transforming valid hmap paths into full absolute paths and concat together
 
     Args:
@@ -289,11 +289,12 @@ def _header_search_paths_for_target(target_name, all_transitive_targets):
         if len(hmap) == 0:
             continue
         if hmap != "." and hmap[0] != "/":
+          if not hmap_name_filter or hmap_name.find(hmap_name_filter) != -1:
             hmap = "$BAZEL_WORKSPACE_ROOT/%s" % hmap
             header_search_paths.append("\"%s\"" % hmap)
 
+    header_search_paths.append("\"$BAZEL_WORKSPACE_ROOT\"") if include_wksp_root
     # We always need to include a search path at workspace root
-    header_search_paths.append("\"$BAZEL_WORKSPACE_ROOT\"")
     return " ".join(header_search_paths)
 
 _XCASSETS = "xcassets"
@@ -466,6 +467,7 @@ def _populate_xcodeproj_targets_and_schemes(ctx, targets, src_dot_dots, all_tran
         }
 
         target_settings["HEADER_SEARCH_PATHS"] = _header_search_paths_for_target(target_name, all_transitive_targets)
+        target_settings["USER_HEADER_SEARCH_PATHS"] = _header_search_paths_for_target(target_name, all_transitive_targets, include_wksp_root = False, hmap_name_filter = 'private_hmap')
 
         target_settings["FRAMEWORK_SEARCH_PATHS"] = _framework_search_paths_for_target(target_name, all_transitive_targets)

```

2020-10-08 02:34 UTC, amberdixon commented
Also FYI I rebased this branch on master.

2020-10-08 17:05 UTC, gyfelton commented
@amberdixon does this help with `could not find module 'XXX' for target 'arm64-apple-ios'; found: x86_64` issue?

2020-10-08 17:40 UTC, amberdixon commented
> @amberdixon does this help with `could not find module 'XXX' for target 'arm64-apple-ios'; found: x86_64` issue?

It does not. But it is the correct change to make. I think once you have added that in, we can land this as-is.

The issue with `could not find module 'XXX' for target 'arm64-apple-ios'; found: x86_64` has existed for a while now ... it was masked by these other issues that we are fixing.

2020-10-08 17:47 UTC, segiddins approved these changes

2020-10-08 19:40 UTC, amberdixon approved these changes
Discussed with Elton in person. We can merge this PR as is and file an issue to add the `-iquote` flag later ... note that the solution it is NOT as simple as updated the USER_HEADER_SEARCH_PATHS ... it's possible the `-iquote` option  can be added by editing OTHER_CFLAGS.

2020-10-08 19:41 UTC, amberdixon commented
Also FYI, you need to bazelisk run on all the iOS projects to get green builds.

2020-10-08 20:04 UTC, gyfelton commented
> I think the only thing you need to do in order to land this change is the following:
> 
> ```
> diff --git a/rules/xcodeproj.bzl b/rules/xcodeproj.bzl
> index 53f706a..219d57a 100644
> --- a/rules/xcodeproj.bzl
> +++ b/rules/xcodeproj.bzl
> @@ -267,7 +267,7 @@ def _framework_search_paths_for_target(target_name, all_transitive_targets):
>                  framework_search_paths.append("\"%s\"" % fi)
>      return " ".join(framework_search_paths)
>  
> -def _header_search_paths_for_target(target_name, all_transitive_targets):
> +def _header_search_paths_for_target(target_name, all_transitive_targets, include_wksp_root = True, hmap_name_filter = None):
>      """Helper method transforming valid hmap paths into full absolute paths and concat together
>  
>      Args:
> @@ -289,11 +289,12 @@ def _header_search_paths_for_target(target_name, all_transitive_targets):
>          if len(hmap) == 0:
>              continue
>          if hmap != "." and hmap[0] != "/":
> -            hmap = "$BAZEL_WORKSPACE_ROOT/%s" % hmap
> -            header_search_paths.append("\"%s\"" % hmap)
> -
> +            if hmap_name_filter == None or hmap.find(hmap_name_filter) != -1:
> +                hmap = "$BAZEL_WORKSPACE_ROOT/%s" % hmap
> +                header_search_paths.append("\"%s\"" % hmap)
> +    if include_wksp_root:
> +        header_search_paths.append("\"$BAZEL_WORKSPACE_ROOT\"")
>      # We always need to include a search path at workspace root
> -    header_search_paths.append("\"$BAZEL_WORKSPACE_ROOT\"")
>      return " ".join(header_search_paths)
>  
>  _XCASSETS = "xcassets"
> @@ -466,6 +467,7 @@ def _populate_xcodeproj_targets_and_schemes(ctx, targets, src_dot_dots, all_tran
>          }
>  
>          target_settings["HEADER_SEARCH_PATHS"] = _header_search_paths_for_target(target_name, all_transitive_targets)
> +        target_settings["USER_HEADER_SEARCH_PATHS"] = _header_search_paths_for_target(target_name, all_transitive_targets, include_wksp_root = False, hmap_name_filter = 'private_hmap')
>  
>          target_settings["FRAMEWORK_SEARCH_PATHS"] = _framework_search_paths_for_target(target_name, all_transitive_targets)
> ```

This is being linked in the newly created issue: https://github.com/bazel-ios/rules_ios/issues/135

2020-10-08 20:28 UTC, merged